### ISSUE TITLE
Add sleep start/stop timestamps to google sheet

### ISSUE THREAD

**Issue by DovOps** [pelo-tech/whoop-google-sheets#3]
Per pelo-tech/whoop-api-spec#5 - @jbpauly requested to add sleep timestamps to the google sheets export. In order to remain backward compatible, these should be added to the rightmost empty columns.

**Comment by DovOps** [comment]
@jbpauly you can now get a fresh copy of the code by re-cloning the spreadsheet in the readme, or by replacing constants.gs and whoop.gs in your local copy.

**Comment by jbpauly** [comment]
Thanks @DovOps, works great.
