### ISSUE TITLE
Day of Week Misaligned

### ISSUE THREAD

**Issue by jbpauly** [pelo-tech/whoop-google-sheets#4]
`Day of Week` values lag by 1 day.

example: 
Date: Tuesday, October 13, 2020
Day of Week: 1 mon

**Comment by DovOps** [comment]
@jbpauly  - Taking a look. Sorry for the delay. I've had this happen on and off and it seemed to be inconsistent (there's a "timezone" associated with the spreadsheet which have caused some of this.

**Comment by DovOps** [comment]
@jbpauly  this should address the issue.
